### ISSUE TITLE
Nan for LSEPool

### ISSUE THREAD

**Issue by ycjing** [VChristlein/dgmp#1]
Hi @VChristlein 

Thank you for this great work! I try to use LSE Pooling method with learnable r. However, I would get nan loss during training. May I ask do you encounter this situation in your experiment? Could you please give me some hints on how this would happen? I would appreciate your help. Thanks!

Best,
Yongcheng

**Comment by VChristlein** [comment]
Hi @ycjing,
I haven't encountered that when using LSE pooling but haven't used it since a while now. The numerical instabilities are actually already taken into account (by subtracting x_max), but maybe r goes to 0? 

Best regards

**Comment by ycjing** [comment]
Hi @VChristlein 

Thank you for the response! I appreciate it. I will see the value of r in training and figure out what happens.

Best,
Yongcheng
